### ISSUE TITLE
Inconsistent pulse testing

### ISSUE THREAD

**Issue by Elewander** [krcools/BEAST.jl#13]
Consider this code
```
using CompScienceMeshes, BEAST
o, x, y, z = euclidianbasis(3)

Γ = meshsphere(1.0, 0.8)
X = raviartthomas(Γ)

sol = 299792458.0
dt, Nt = 3/sol,200

dirac = timebasisdelta(dt, Nt)
pulse = timebasiscxd0(dt, Nt)

duration, delay, amplitude = 150.0/sol, 300.0/sol, 1.0
direction, polarisation = z, x
gaussian = creategaussian(duration, delay, amplitude)
gaussian_delayed = creategaussian(duration, delay+dt, amplitude)

E = planewave(polarisation, direction, gaussian, sol)
E_delayed = planewave(polarisation, direction, gaussian_delayed, sol)
Ederiv = planewave(polarisation, direction, derive(gaussian), sol)

Vreference = assemble(Ederiv, X ⊗ pulse)
Vtheory = assemble(E, X ⊗ dirac) - assemble(E_delayed, X ⊗ dirac)
```
There might be 2 issues with the pulse (`timebasiscxd0`) testing:
- it seems that there is a delay of 1 time step as the first column of `Vreference` is all 0
- Considering the following derivation i think that  `Vreference` should be equal to `Vtheory` but instead there is a `dt` scaling in this code and effectively `Vreference[:,2:end]/dt` equals `Vtheory[:,1:end-1]` (`[:,2:end]` and `[:,1:end-1]` because of the delay of 1 time step described in the first point)

<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{array}{cl}&space;\int_\mathbb{R}&space;p(t-i\Delta&space;t)\frac{\partial&space;f}{\partial&space;t}(t)dt&space;&&space;=-\int_\mathbb{R}&space;\frac{\partial&space;p}{\partial&space;t}(t-i\Delta&space;t)f(t)dt&space;\\&space;&&space;=-\int_\mathbb{R}&space;(\delta(t-(i-1)\Delta&space;t)-\delta(t-i\Delta&space;t))f(t)dt&space;\\&space;&&space;=&space;\int_\mathbb{R}&space;\delta(t-i\Delta&space;t)f(t)dt&space;-&space;\int_\mathbb{R}&space;\delta(t-i\Delta&space;t)f(t-\Delta&space;t)dt&space;\end{array}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{array}{cl}&space;\int_\mathbb{R}&space;p(t-i\Delta&space;t)\frac{\partial&space;f}{\partial&space;t}(t)dt&space;&&space;=-\int_\mathbb{R}&space;\frac{\partial&space;p}{\partial&space;t}(t-i\Delta&space;t)f(t)dt&space;\\&space;&&space;=-\int_\mathbb{R}&space;(\delta(t-(i-1)\Delta&space;t)-\delta(t-i\Delta&space;t))f(t)dt&space;\\&space;&&space;=&space;\int_\mathbb{R}&space;\delta(t-i\Delta&space;t)f(t)dt&space;-&space;\int_\mathbb{R}&space;\delta(t-i\Delta&space;t)f(t-\Delta&space;t)dt&space;\end{array}" title="\begin{array}{cl} \int_\mathbb{R} p(t-i\Delta t)\frac{\partial f}{\partial t}(t)dt & =-\int_\mathbb{R} \frac{\partial p}{\partial t}(t-i\Delta t)f(t)dt \\ & =-\int_\mathbb{R} (\delta(t-(i-1)\Delta t)-\delta(t-i\Delta t))f(t)dt \\ & = \int_\mathbb{R} \delta(t-i\Delta t)f(t)dt - \int_\mathbb{R} \delta(t-i\Delta t)f(t-\Delta t)dt \end{array}" /></a>

**Comment by krcools** [comment]
You are right on both accounts. The scaling for pulse testing has been modified. I did not shift the testing for pulse, but for delta, since this is more consistent in my view. @shakisparki, let me know if this has any effect on your simulations...
