### ISSUE TITLE
Weld function broken? v0.7

### ISSUE THREAD

**Issue by shakisparki** [krcools/BEAST.jl#25]
Some issue finding length of a StaticArray when using weld in CompScienceMeshes after migrating to BEAST v1.0.0. Stacktrace:

![image](https://user-images.githubusercontent.com/26871554/44158782-8373f080-a0ad-11e8-8554-d6f61ff0f91c.png)

**Comment by shakisparki** [comment]
![image](https://user-images.githubusercontent.com/26871554/44163591-c1781100-a0bb-11e8-9c0f-181e634ed9a6.png)

**Comment by krcools** [comment]
This is due to a world age issue in using together `StaticArrays` and `CollisionDetection`. Check out explicitly the lastest `CollisionDetection` to use the fix:

```
pkg>add CollisionDetection#master
```

**Comment by krcools** [comment]
Did that fix it?

**Comment by shakisparki** [comment]
Yeah that seems to fix it. 
Thanks.
