### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by shipengcheng1230** [krcools/BEAST.jl#29]
Hello, I would like to try your package but I cannot installed it on Julia 1.0.3:
```julia
(v1.0) pkg> add https://github.com/krcools/BEAST.jl
   Cloning git-repo `https://github.com/krcools/BEAST.jl`
  Updating git-repo `https://github.com/krcools/BEAST.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package StaticArrays [90137ffa]:
 StaticArrays [90137ffa] log:
 ├─possible versions are: [0.0.1-0.0.11, 0.1.0-0.1.5, 0.2.0-0.2.1, 0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.1, 0.6.0-0.6.6, 0.7.0-0.7.2, 0.8.0-0.8.3, 0.9.0-0.9.2, 0.10.0, 0.10.2] or uninstalled
 ├─restricted to versions 0.8.3-0.9 by BEAST [bb4162c7], leaving only versions [0.8.3, 0.9.0-0.9.2]
 │ └─BEAST [bb4162c7] log:
 │   ├─possible versions are: 1.0.0 or uninstalled
 │   └─BEAST [bb4162c7] is fixed to version 1.0.0+
 └─restricted to versions 0.10.2 by an explicit requirement — no versions left
```

Perhaps a loose of version requirements would work? It probably involves some compatible test. Thanks!

**Comment by krcools** [comment]
I had to introduce this upper bound because the new StaticArrays broke BEAST. Will fix this in a new release. In the meantime, try:

```
pkg>add BEAST#master
pkg>add CompScienceMeshes#master
```

Let me know if this does not fix it.

What is your use case? Please could you let me know if something is missing currently in BEAST.

**Comment by shipengcheng1230** [comment]
The master branch now works perfectly! Thank you!

 I am trying to do some linear elasticity problem and would like to compare with the analytical solution,  for instance, [DC3D](http://www.bosai.go.jp/study/application/dc3d/DC3Dhtml_E.html). Haven't tried yet 😄 .
