### ISSUE TITLE
Perfect Conduction

### ISSUE THREAD

**Issue by marrdoc** [krcools/BEAST.jl#32]
Hi! In the readme it says that the efie.jl is for a perfectly conducting sphere. Could you please tell me where this enters the code and whether it can be changed?

Thank you very much!

**Comment by krcools** [comment]
The sphere part is simple; this is because the mesh loaded is spherical. Other simple spheres can be constructed using `meshrectangle` and `meshcuboid`, which are part of the `CompScienceMeshes` package.

The material, i.e. perfectly conducting, is implied by the choice of integral equations. For an example involving dielectric (and thus penetrable) objects, see [`examples/pmchwt.jl`](https://github.com/krcools/BEAST.jl/blob/master/examples/pmchwt.jl). You can see that for this more general case two unknown current densities are involved.

Can you tell me more about your specific problem?

**Comment by marrdoc** [comment]
Thx for the quick answer!

I want to make simulations of metallic nano particles (e.g. Au, Ag) and extract scattering/extinction/absorption data. I worked with a python library on that before but that was slow as hell. Now I gave julia a try and wanted to check whether there is a BEM package or something for julia. This is why I came upon your repository.

**Comment by krcools** [comment]
Are these Au, Ag particles modeled as finite conductivity dielectrics? With complex permittivity? In that case it should be fairly straightforward to start from `pmchwt.jl` and turn it into what you need. I never tried complex wavenumbers and material parameters so I'd be curious to see if the code is robust in this scenario.

I assume you will want to simulate a large number of these particles? My code is not accelerated by FMM or H-matrix techniques so you might be disappointed by performance. For simulations up to say 10,000 degrees of freedom it should be acceptable.

**Comment by marrdoc** [comment]
They are modelled according to a [Drude electric function](https://en.wikipedia.org/wiki/Drude_model). This is a coplex valued function for the permitivity \epsilon. Hence also the wavenumber becomes complex. Thank you for the hint I will have a look!

No, at the moment I am just looking for anything that can handle a loop over an energy range with a sphere with let's say 4000 nodes in reasonable time and without crashing.

Is the pmchwt.jl also working with Galerkin?

**Comment by krcools** [comment]
As long as you know the effective permittivity as a complex function of frequency you should be okay.

Assembly of an interaction matrix for 4000 DoFs should be around two minutes for the dielectric case. Total run-time depends on the number of frequency samples.

Yes, `pmchwt.jl`, and in fact all solvers supported by this package are of Galerkin type.

**Comment by marrdoc** [comment]
Yes i know this. Where does the permittivity enter in the script? What is \kappa and \eta?

Two minutes would be nice. Python with cpython took me about 30 Minutes for one run. With 50-100 Frequency samples this is quite long!

Ah, nice! Thx for the effort by the way!

**Comment by krcools** [comment]
$\kappa$ is the wave number: $\kappa = \omega \sqrt{\epsilon \mu}$

$\eta$ is the medium impedance: $\eta = \sqrt{\frac{\mu}{\epsilon}}$

**Comment by marrdoc** [comment]
Ah, thank you!

BTW: what is your (main) purpose that you wrote BEAST for?

**Comment by krcools** [comment]
EM simulations in the MHz and GHz range for antenna design/placement among other things. A former colleague of mine looked into nano-particles as you do. I remember the challenge lies in computing the interaction integrals with sufficient accuracy. I this turns out to be a problem in your usage case, I can refer you to his publications on how to stabilize the solver.

**Comment by marrdoc** [comment]
Interesting. What was your motivation to do it in julia?

May I ask you if you could give me the reference anyway? ;)

**Comment by krcools** [comment]
Ease of programming. Expressiveness without efficiency trade-offs. Built-in package manager, testing tools, meta-programming. The ability to create domain specific languages. Good integration with GitHub and friends. Portability (currently the CI runs BEAST on linux/macos/windows).

The reference I was talking about is [Peeters at al., Calculation of MoM Interaction Integrals in Highly Conductive Media](https://ieeexplore.ieee.org/document/6058615)

**Comment by marrdoc** [comment]
Interesting. I just started this week to dig into julia.

Thank you!

**Comment by marrdoc** [comment]
Ok, i have another issue. In order to compute the extinction cross section I need to calculate C^{ext} = \frac{4*\pi}{\kappa}*imag(plarization*farfield(direction)).

I tried this by doing:
`far_field = potential((MWFarField3D(κ*im), d, u, X))
 extinction_cross_vec[count] = 4*π*imag(farfield[3])/k_2(energy)`
where "energy" is my running parameter in the loop over the energy range.

I get this error message:
_ERROR: LoadError: MethodError: no method matching potential(::Tuple{MWFarField3D{Complex{Float64}},StaticArrays.SArray{Tuple{3},Float64,1,3},Array{Complex{Float64},1},BEAST.RTBasis{Float64,Mesh{3,3,Float64},StaticArrays.SArray{Tuple{3},Float64,1,3}}})_

So my question is the potential-function doing? And is "X" the 3D-space or a function space? I assume I only need the MWFarField3D but somehow the solution "u" does not enter there but only in the potential if I get this right. And about the "MWFarField3D" itself, I guess the argument is a direction of the far field. But Why is it in the example imaginary?

**Comment by krcools** [comment]
I will write some documentation for this. In the meantime:

- I think your `MethodError` is just the result of putting two pairs of parentheses around the arguments.
- For implementation reasons, I use the propagation constant `gamma = im*kappa` as the fundamental parameter. To avoid confusion, it is best to create the kernel using explicit keywords: `FF = MWFarField3D(wavenumber=kappa)`.
- `d` is a vector of directions into which to compute the far field. For scatter cross sections I guess only the direction the excitation was coming from would be required. Still you have to make a vector of points, e.g. `[point(0,0,-1)]`.
- `u` is the vector of expansion coefficients w.r.t. to the basis `X` of the finite element space.
- So yes, `X` is the function space. In many cases constructed by calling `raviartthomas(Gamma)`.

**Comment by krcools** [comment]
Another important thing to keep in mind however, is that you need to add (with certain coefficients i cannot reproduce just now) the far field radiated by the two unknown current densities: the magnetic current and electric current.

I'll update `pmchwt.jl` to reflect this.

**Comment by marrdoc** [comment]
Thank you! I'll try to implement this.

**Comment by krcools** [comment]
I updated `pmchwt.jl` to include the correct way to compute the far field. The value at theta=pi now should be (maybe up to a constant normalization factor) the cross section of the target.

**Comment by marrdoc** [comment]
Thank you! I'll see if it works for me!
