### ISSUE TITLE
Varform for building ScalarTrace broken

### ISSUE THREAD

**Issue by shakisparki** [krcools/BEAST.jl#35]
`@varform η*T[k,j] == f[ntrace(k,γ₁)]`

returns error

`MethodError: objects of type Mesh{3,2,Float64} are not callable`

```
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by krcools** [comment]
Can you provide a more complete script? Are you using raviartthomas? What is f?

**Comment by krcools** [comment]
For example, this works for me:

```
using CompScienceMeshes
using BEAST

m = meshrectangle(1.0, 1.0, 0.2, 3)
X = raviartthomas(m, skeleton(m,1))

n = boundary(m)
x = ntrace(X,n)

V₀ = 1.0
f = ScalarTrace(p -> V₀)

assemble(f, x)
```

**Comment by shakisparki** [comment]
`Capacitor.jl` in Examples is a good example.
Yes, assemble works, It's when you write it in Var-form like this
`@varform η*T[k,j] == f[ntrace(k,γ₁)]` 
which used to work in previous versions I believe.
