### ISSUE TITLE
Broken code: ScalarTrace not Callable

### ISSUE THREAD

**Issue by shakisparki** [krcools/BEAST.jl#4]
Running a statement like below
`RT = rt_ports(Γ,[γ₁,γ₂])` 
 `f=ScalarTrace(p->1.0)`
`assemble(f,ntrace(RT,γ₁))`

results in errors like:
> _objects of type BEAST.ScalarTrace are not callable_
> MethodError: no method matching `integrand(::BEAST.ScalarTrace,...`

That’s probably because Line 143  and 144 of helmholtop.jl have been commented out.
[Line 143](https://github.com/krcools/BEAST.jl/blob/master/src/helmholtz2d/helmholtzop.jl#L143)
[Line 144](https://github.com/krcools/BEAST.jl/blob/master/src/helmholtz2d/helmholtzop.jl#L144)

**Comment by krcools** [comment]
Thanks. I uncommented these lines. Let me know if this breaks something. All tests passed but...
