### ISSUE TITLE
JuliaCon minisymposium

### ISSUE THREAD

**Issue by j-fu** [krcools/BEAST.jl#44]
Hi, I am Jürgen Furhmann  and work on [VoronoiFVM](https://github.com/j-fu/VoronoiFVM.jl).
I am organizing a minisymposium at JuliaCon 2020, see https://github.com/users/j-fu/projects/1
Would you be interested ?

**Comment by krcools** [comment]
Dear Juergen, 

thank you for contacting me about this. I am indeed very interested to contribute. When do you need a commitment by? Maybe we can continue this conversation by email. My contact details can be found at:

(https://www.tudelft.nl/staff/k.cools/)
