### ISSUE TITLE
MWSingleLayerTDIO using speed of light

### ISSUE THREAD

**Issue by shakisparki** [krcools/BEAST.jl#5]
Using the single layer time domain operator appropriately with the speed of light, 
and a suitable time step for a simple example like in [tdefie.jl](https://github.com/krcools/BEAST.jl/blob/master/examples/tdefie.jl)  where:
`T = MWSingleLayerTDIO(c, -1/c, -c, 2, 0)`  or `T = MWSingleLayerTDIO(c)`
`Δt, Nt = 3e-10, 200`
Results in current coefficients of the order 1e-47, growing with time, and eventually `NaN` values. Same applies to structures of different geometry.

**Comment by krcools** [comment]
Did you rescale the geometry and the timestep accordingly?

**Comment by krcools** [comment]
You're right, there is a bug. I am fixing it. Should get it soon...

**Comment by shakisparki** [comment]
Great!

**Comment by krcools** [comment]
Give it a try now. To see where you have to modify the code, check `examples/tdefie.jl`. The speed of light affects the time step, the parameters passed at creation of the integral operator, and the definition of the incident plane wave.

**Comment by shakisparki** [comment]
Seems to work fine now.
Surely the 3rd argument in [Line 18](https://github.com/krcools/BEAST.jl/blob/master/examples/tdefie.jl#L18) should be `amplitude`?
