### ISSUE TITLE
path for examples

### ISSUE THREAD

**Issue by RainerHeintzmann** [krcools/BEAST.jl#58]
I tried running an example with the current GitHub version and hit a few issues:
I noted that the path for the examples together with reading some repository-contained data is a bit cumbersome to use in practice as it requires a `cd()` to the examples folder.
How about starting the examples like this:
```julia
d = dirname(pathof(BEAST)) * "/../examples"
Γ = readmesh(joinpath(d,"sphere2.in"))
```
It turns out, Julia in Windows can deal with the "/" as path separators, so this is tested in Windows ...
in addition you may want to add 
```julia
using LinearAlgebra
```
as the `norm` function is not part of julia Base.

**Comment by krcools** [comment]
In some examples like `efie.jl`, I am already taking this approach. I will change the remaining examples to do the same.

**Comment by krcools** [comment]
Does the current approach:

```
Γ = readmesh(joinpath(@__DIR__,"sphere2.in"))
```

not lead to loading the asset, regardless the current working directory?

**Comment by RainerHeintzmann** [comment]
Well, it may do so if you run the code, but if you cut-and-paste (which is what I most of the times do when testing), it does not work.

**Comment by krcools** [comment]
Ah, understood. Could I suggest VSCode's alt-enter execution mode? It seems to respect the @__DIR__ macro. Anyways, for now I will use the `pathof` approach.

**Comment by RainerHeintzmann** [comment]
Thanks for changing this. There are a few more examples that seem to use @DIR, like planewave.jl.
But this is easy to change anyway...
I had been using Strg-Enter as execution mode. What is the difference to alt-enter, which indeed seems to work with @DIR?
