### ISSUE TITLE
Inconsistent Contour Construction

### ISSUE THREAD

**Issue by shakisparki** [krcools/BEAST.jl#6]
Certain mesh discretization sizes for certain geometries e.g simply chaging [tdefie.jl - Line 8](https://github.com/krcools/BEAST.jl/blob/master/examples/tdefie.jl#L8) to
`**Δx = 1/10**`
`Γ = meshrectangle(1.0,1.0,Δx)`
results in 
> LoadError: inconsistent contour construction!
in WiltonInts84

Using `Δx = 1/8` or `Δx = 1/12` for example doesn't return any error.

**Comment by krcools** [comment]
Short answer: use a slightly different dx. Long answer: it's complicated.

**Comment by krcools** [comment]
or a different quadrule, or a different speedoflight

**Comment by krcools** [comment]
or a different dt. That's probably the best/easiest

**Comment by shakisparki** [comment]
Yeah, a different `Δt` or `Δx` seems to be the easiest way around

**Comment by krcools** [comment]
Can you give the precise example that triggered this?

**Comment by shakisparki** [comment]
running [tdefie.jl](https://github.com/krcools/BEAST.jl/blob/master/examples/tdefie.jl#L8) with 
```
Δx = 1/10
Γ = meshrectangle(1.0,1.0,Δx)
```
for example. Or using a smaller  time step resolution like 
```
Δx = 1/8
Δt = 0.008/sol
Γ = meshrectangle(1.0,1.0,Δx)
```
