### ISSUE TITLE
Broken assemble for rtports in freq domain - RTBasis.pos 

### ISSUE THREAD

**Issue by shakisparki** [krcools/BEAST.jl#7]
new position vector in RTBasis type [RTBasis](https://github.com/krcools/BEAST.jl/blob/master/src/bases/rtspace.jl#L7)  
causes this freq domain code to fail
`RT = rt_ports(Γ,[γ₁,γ₂])`
`T = MWSingleLayer3D(im*κ)`
`Z = assemble(T,RT,RT)`
because `rtports` has no implementation for populating the position vector yet. Which is accessed by 
[subset](https://github.com/krcools/BEAST.jl/blob/master/src/bases/rtspace.jl#L14)  <- [assemble!](https://github.com/krcools/BEAST.jl/blob/master/src/operator.jl#L117)

I will try and include this later, although I wonder how the `position` value will be averaged for the "global" component of `rtports` as in [Line 54](https://github.com/krcools/BEAST.jl/blob/master/src/bases/rtspace.jl#L54)

**Comment by krcools** [comment]
Try again. I could run `examples/capacitor.jl`. Assembly does not crash, but the positions cannot be trusted (all entries of the pos field are set to the origin). A better solution is required.

**Comment by shakisparki** [comment]
Yes, setting all entries to zero should allow assembly run without throwing an error. As long as `pos` isn't utilised in a way that jeopardises the results of the function, i should be able to manage it this way for now.
