### ISSUE TITLE
MWSingleLayer3D and MWSingleLayerField3D

### ISSUE THREAD

**Issue by sbadrian** [krcools/BEAST.jl#71]
If I did not miss something, the type MWSingleLayerField3D lacks the alpha and beta members that MWSingleLayer3D has. This is not critical as for most practical purposes it boils down to scaling with the impedance. It is, however, a mild inconsistency with MWSingleLayer3D.

I would propose to
- make MWSingleLayerField3D fully compatible with MWSingleLayer3D
- add a function that allows constructing an instance of MWSingleLayerField3D from an instance of MWSingleLayer3D (this also for the double layer)

If approved of I am happy to do this.

**Comment by krcools** [comment]
Sure, thank you. Maybe with a constructor that defaults to the actual single layer operator.

**Comment by sbadrian** [comment]
PR #74 implements this. I am not sure I got what you meant by 

> defaults to the actual single layer operator.

Is there something that should be added?
