### ISSUE TITLE
Singularity in Computing DoubleLayer Operator

### ISSUE THREAD

**Issue by shakisparki** [krcools/BEAST.jl#9]
Testing the double layer operator `K` with `nxRWG` and the BuffaChristiansen as the trial basis results in `NaN` values for certain interactions.
e.g 
```
RT = raviartthomas(Γ); BC = buffachristiansen(Γ)
K = MWDoubleLayer3D(im*κ)
M  = assemble(K,RT,BC)
```
Tried with both open and closed structures

**Comment by krcools** [comment]
Is this still an issue? Tried to reproduce but it seems to be okay now. Does this happen for a specific geometry or is this a very common occurrence?

**Comment by shakisparki** [comment]
I think it should be fine now. I'll just close the issue.
